FROM python:3.10-slim

WORKDIR /ui

RUN apt-get update && \
    apt-get install -y --no-install-recommends libgomp1 && \
    rm -rf /var/lib/apt/lists/*

COPY ui/requirements.txt .
RUN pip install --upgrade pip && \
    pip install --no-cache-dir -r requirements.txt

COPY ui .

CMD ["streamlit", "run", "app.py", "--server.port=48092", "--server.address=0.0.0.0"]