server:
  port: 8088
  servlet:
    context-path: /auth
spring:
  mvc:
    static-path-pattern: /**
  web:
    resources:
      static-locations: classpath:/static/
  datasource:
    url: jdbc:postgresql://localhost:45432/bank_z
    username: root
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  kafka:
    bootstrap-servers: kafka:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      group-id: auth-service-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:48088/auth

app:
  jwt:
    secret: "A3F8z9PqX6wYbN2cV5sD7rGtHjK4mLpQ1vB9nZx0C" # 32 символа
    expirationMs: 86400000 # 24 часа

#Swagger
springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /api-docs

logging:
  level:
    root: INFO
    z.bank: DEBUG
    org.springframework.security: DEBUG
    org.springdoc: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      enabled: true
      show-details: always
    prometheus:
      enabled: true
    heapdump:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true
    tags:
      application: bank-z-login