services:
  createclients:
    build: ./
#    image: your-registry/createclients:latest
    container_name: createclients
    ports:
      - "${CREATE_CLIENTS_PORT}:48085"
    networks:
      bank_z:  # Явно подключаем к сети
        aliases:
          - createclients  # Добавляем DNS-алиас
    environment:
      JAVA_OPTS: "${CREATECLIENTS_JAVA_OPTS}"
      SPRING_KAFKA_BOOTSTRAP_SERVERS: "kafka:49092"
      KAFKA_TOPIC_CLIENT: "${KAFKA_TOPIC_CLIENT}"
      SPRING_DATASOURCE_URL: "jdbc:postgresql://postgres_bz:5432/${POSTGRES_DB}"
      SPRING_DATASOURCE_USERNAME: "${POSTGRES_USER}"
      SPRING_DATASOURCE_PASSWORD: "${POSTGRES_PASSWORD}"
    labels:
      - "type=business"
 
networks:
  bank_z:
    external: true