services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    container_name: zookeeper_bz
    environment:
      ZOOKEEPER_CLIENT_PORT: 42181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_INIT_LIMIT: 10
      ZOOKEEPER_SYNC_LIMIT: 5
    healthcheck:
      test: ["CMD-SHELL", "echo ruok | nc localhost 42181 | grep imok"]
      interval: 10s
      timeout: 20s
      retries: 15
    ports:
      - "42181:42181"
    volumes:
      - zk-data:/var/lib/zookeeper/data
      - zk-log:/var/lib/zookeeper/log
    networks:
      - bank_z

  kafka:
    build: . # Указываем путь к Dockerfile
    #image: confluentinc/cp-kafka:7.4.0
    container_name: kafka_bz
    depends_on:
      zookeeper:
        condition: service_healthy
    environment:
      KAFKA_OPTS: -javaagent:/opt/jmx_exporter/jmx_prometheus_javaagent.jar=7071:/opt/jmx_exporter/jmx-config.yml
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:42181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:49092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: "1"
      KAFKA_LOG_DIRS: "/var/lib/kafka/data-new"  # Путь для логов
      KAFKA_JMX_PORT: 9997
      KAFKA_JMX_HOSTNAME: kafka
      JMX_PORT: 9997
    healthcheck:
      test: ["CMD-SHELL", "kafka-topics --bootstrap-server kafka:9092 --list || exit 1"]
      interval: 20s
      timeout: 30s
      retries: 15
    ports:
      - "9092:9092"
      - "49092:49092"
      - "49997:9997" # JMX порт
      - "47071:7071" # JMX для Prometheus
    volumes:
      - kafka-data:/var/lib/kafka/data
    networks:
      - bank_z
      
  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui_bz
    depends_on:
      - kafka
    environment:
      KAFKA_CLUSTERS_0_NAME: local-kafka
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
      KAFKA_CLUSTERS_0_ZOOKEEPER: zookeeper:42181
      KAFKA_CLUSTERS_0_JMXPORT: 9997
      KAFKA_CLUSTERS_0_JMXSSL: "false"
    ports:
      - "48480:8080"  # Измененный порт для веб-интерфейса
    networks:
      - bank_z

volumes:
  zk-data:
  zk-log:
  kafka-data:

networks:
  bank_z:
    external: true