version: '3.9'

services:
  # Postgres Database
  db:
    container_name: pg_bank_z
    image: postgres:14-alpine
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: bank_z
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5438:5432"
    networks:
      - zbank-network
  
  # PgAdmin Interface
  pgadmin:
    container_name: pgadmin_bank_z
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: noemail@noemail.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "8087:80"
    networks:
      - zbank-network
      
  # Zookeeper
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - zbank-network

  # Kafka
  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,PLAINTEXT_HOST://0.0.0.0:29092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
    ports:
      - "9092:9092"
      - "29092:29092"
    networks:
      - zbank-network

  # Prometheus
  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./configuration/:/etc/prometheus/
      - ./data/:/prometheus/
    container_name: prometheus
    hostname: prometheus
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    ports:
      - 9777:9090
    restart: unless-stopped
    environment:
      TZ: "Europe/Moscow"
    extra_hosts:  # Добавляем хост Windows в контейнер
      - "host.docker.internal:host-gateway"
    networks:
      - zbank-network
  
  #node-exporter    
  node-exporter:
    image: prom/node-exporter
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    container_name: exporter
    hostname: exporter
    command:
      - --path.procfs=/host/proc
      - --path.sysfs=/host/sys
      - --collector.filesystem.ignored-mount-points
      - ^/(sys|proc|dev|host|etc|rootfs/var/lib/docker/containers|rootfs/var/lib/docker/overlay2|rootfs/run/docker/netns|rootfs/var/lib/docker/aufs)($$|/)
    ports:
      - 9107:9100
    restart: unless-stopped
    environment:
      TZ: "Europe/Moscow"
    networks:
      - zbank-network
  
  # Grafana
  grafana:
    image: grafana/grafana
    user: root
    depends_on:
      - prometheus
    ports:
      - 3007:3000
    volumes:
      - ./grafana:/var/lib/grafana
      - ./grafana/provisioning/:/etc/grafana/provisioning/
    container_name: grafana
    hostname: grafana
    restart: unless-stopped
    environment:
      TZ: "Europe/Moscow"
    networks:
      - zbank-network

  # Application
#  zbank-app:
#    build: .
#    container_name: zbank-app
#    ports:
#      - "8080:8080"
#    environment:
#      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:9092
#      - KAFKA_TOPIC_LOGS=bank-logs
#      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/bank_z
#      - SPRING_DATASOURCE_USERNAME=root
#      - SPRING_DATASOURCE_PASSWORD=root
#    depends_on:
#      - db
#      - kafka
#    networks:
#      - zbank-network

volumes:
  postgres_data:
  grafana_data:

networks:
  zbank-network:
    driver: bridge