services:
  createcard:
    build: ./
#    image: your-registry/createcard:latest
    container_name: createcard
    ports:
      - "${CREATE_CARD_PORT}:48084"
    networks:
      bank_z:  # Явно подключаем к сети
        aliases:
          - createcard  # Добавляем DNS-алиас
    environment:
      JAVA_OPTS: "${CREATECARD_JAVA_OPTS}"
      SPRING_KAFKA_BOOTSTRAP_SERVERS: "kafka:9092"
      KAFKA_TOPIC_CLIENT: "${KAFKA_TOPIC_CLIENT}"
      SPRING_DATASOURCE_URL: "jdbc:postgresql://postgres_bz:5432/${POSTGRES_DB}"
      SPRING_DATASOURCE_USERNAME: "${POSTGRES_USER}"
      SPRING_DATASOURCE_PASSWORD: "${POSTGRES_PASSWORD}"
    labels:
      - "type=business"
 
networks:
  bank_z:
    external: true