FROM jenkins/jenkins:lts

USER root

# Установка Python и зависимостей
RUN apt-get update && \
    apt-get install -y python3 python3-pip zip && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

USER jenkins