global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Для node-exporter в network_mode: host
  - job_name: 'postgresql-node-exporter'
    static_configs:
      - targets: ['host.docker.internal:9100']
        labels:
          instance: 'postgres-node'

  # Для postgres-exporter
  - job_name: 'postgres-exporter'
    static_configs:
      - targets: ['postgres-exporter:9187']
        labels:
          instance: 'postgres-db'

  # Для InfluxDB 
  - job_name: 'influxdb'
    static_configs:
      - targets: ['influxdb:8086']
      
  # Для мониторинга Генератора нагрузки
  - job_name: windows_exporter
    static_configs:
      - targets: ['host.docker.internal:9182']
    
  # Kafka
  - job_name: 'kafka-jmx-exporter'
    static_configs:
      - targets: ['kafka:7071']
      
#  - job_name: 'kafka-exporter'
#    static_configs:
#      - targets: ['kafka-exporter:9308']
    
#  - job_name: 'kafka-node-exporter'
#    static_configs:
#      - targets: ['kafka-node-exporter:9102']
      
#  - job_name: 'kafka-brokers'
#    static_configs:
#      - targets: ['kafka:9092']
#    metrics_path: /metrics
    
  - job_name: 'jvm-services'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['createcard:48084', 'createclients:48085']
  
  - job_name: 'jvm-mock'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['mockepa:48081', 'mockgos:48082']

  - job_name: "docker"
    static_configs:
      - targets: ["host.docker.internal:48080"]  # cAdvisor
           
alerting:
  alertmanagers:
    - static_configs:
        - targets: []
    
  
