global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Для node-exporter в network_mode: host
  - job_name: 'postgresql-node-exporter'
    static_configs:
      - targets: ['host.docker.internal:9100']  # Специальное имя для Docker Desktop
        labels:
          instance: 'postgres-node'

  # Для postgres-exporter
  - job_name: 'postgres-exporter'
    static_configs:
      - targets: ['postgres-exporter:9187']
        labels:
          instance: 'postgres-db'

  # Для InfluxDB (если нужно)
  - job_name: 'influxdb'
    static_configs:
      - targets: ['influxdb:8086']
      
  # Для мониторинга Генератора нагрузки
  - job_name: windows_exporter
    scrape_interval: 5s
    static_configs:
    - targets: ['host.docker.internal:9182']

  # JVM Сервиса создания карты
  - job_name: create_card
    scrape_interval: 5s
    metrics_path: /metrics
    static_configs:
    - targets: ['host.docker.internal:9000']
    
  # Kafka
  - job_name: 'kafka-exporter'
    static_configs:
    - targets: ['kafka-exporter:9308']
    
  - job_name: 'kafka-node-exporter'
    static_configs:
      - targets: ['kafka-node-exporter:9102']

alerting:
  alertmanagers:
    - static_configs:
        - targets: []
    
  
