services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    container_name: zookeeper_bz
    environment:
      ZOOKEEPER_CLIENT_PORT: 42181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_INIT_LIMIT: 10
      ZOOKEEPER_SYNC_LIMIT: 5
    healthcheck:
      test: ["CMD-SHELL", "echo ruok | nc localhost 42181 | grep imok"]
      interval: 10s
      timeout: 20s
      retries: 15
    ports:
      - "42181:42181"
    volumes:
      - zk-data:/var/lib/zookeeper/data
      - zk-log:/var/lib/zookeeper/log
    networks:
      - bank_z

  kafka:
    image: confluentinc/cp-kafka:7.4.0
    container_name: kafka_bz
    depends_on:
      zookeeper:
        condition: service_healthy
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:42181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:49092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: "1"
      KAFKA_LOG_DIRS: "/var/lib/kafka/data-new"  # Новый путь для логов
    healthcheck:
      test: ["CMD-SHELL", "kafka-topics --bootstrap-server kafka:9092 --list || exit 1"]
      interval: 20s
      timeout: 30s
      retries: 15
    ports:
      - "9092:9092"
      - "49092:49092"
    volumes:
      - kafka-data:/var/lib/kafka/data
    networks:
      - bank_z

volumes:
  zk-data:
  zk-log:
  kafka-data:

networks:
  bank_z:
    driver: bridge