services:
  postgres:
    image: postgres:14
    container_name: postgres_bz
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-root}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-root}
      POSTGRES_DB: ${POSTGRES_DB:-bank_z}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-root} -d ${POSTGRES_DB:-bank_z}"]
      interval: 5s
      timeout: 5s
      retries: 10
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - /sys/fs/cgroup:/sys/fs/cgroup:ro  # Для мониторинга CPU/Memory
      - /var/lib/docker/volumes:/var/lib/docker/volumes:ro  # Для мониторинга volumes
    deploy:
      resources:
        limits:
          cpus: '2'  # Явное ограничение CPU
          memory: 4G  # Ограничение памяти
    ports:
      - "45432:5432"
    networks:
      - bank_z

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_bz
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL:-noemail@noemail.com}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD:-root}
    ports:
      - "48087:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - bank_z

  postgres-exporter:
    image: prometheuscommunity/postgres-exporter
    container_name: postgres-exporter_bz
    environment:
      DATA_SOURCE_NAME: "postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}?sslmode=disable"
    ports:
      - "49187:9187"
    depends_on:
      - postgres
    networks:
      - bank_z
      
  postgres-node-exporter:
    image: prom/node-exporter
    container_name: postgres_node_exporter_bz
    # Вариант 1: Без публикации портов (доступ через host network)
    network_mode: host  # Полный доступ к системным метрикам
    pid: "host"
    volumes:
      - /:/rootfs:ro
      - /sys:/sys:ro
      - /proc:/proc:ro
    command:
      - --path.rootfs=/rootfs
      - --collector.disable-defaults
      - --collector.cpu
      - --collector.meminfo
      - --collector.diskstats
##    ports:
##      - "49100:9100"
    restart: unless-stopped
    depends_on:
      - postgres

volumes:
  pg_data:
    driver: local
  pgadmin_data:
    driver: local

networks:
  bank_z:
    external: true