services:
  jenkins:
    build: .  # Используем наш Dockerfile
    # image: jenkins/jenkins:lts
    ports:
      - "58080:8080"
      - "50000:50000"
    volumes:
      - jenkins-data:/var/jenkins_home
      - ./scripts:/scripts  # Папка со скриптами
      - /path/on/host:/path/in/container
    networks:
      - bank_z

volumes:
  jenkins-data:

networks:
  bank_z:
    external: true