apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090  # Используем имя сервиса из docker-compose
    isDefault: true
    version: 1
    editable: true