server:
  port: 48089

# Actuator settings
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
    prometheus:
      enabled: true
    heapdump:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true


